### ISSUE TITLE
Gracefully Handle CSVs Marked Read-Only

### ISSUE THREAD

**Issue by sghill** [SteveMoyer/nDump#2]
If CSVs are not checked out from TFS, nDump throws an unhandled exception and crashes with the following message when exporting:

`Unhandled Exception: System.UnauthorizedAccessException: Access to the path [...] is denied.`

**Comment by SteveMoyer** [comment]
Any thoughts on graceful way to hande this?  Can wrap it in a more specific exception but I don't know that there is a reasonable way to continue processing.  "Unhandled Exception: nDump.TFSSucksException:  You need to check out file [...]"

**Comment by SteveMoyer** [comment]
Maybe vary the snark:  "Are you sure you don't want to use a better version control system?  Or you can just keep dancing with the read only flag."

**Comment by sghill** [comment]
I'd like it to print a message like `nDump cannot access your CSVs. Are they checked out (TFS) or modifiable?` and exit without throwing an exception and the dialog box "nDump quit unexpectedly". :-D

**Comment by SteveMoyer** [comment]
Posted nDump 0.3.3 which should resolve the issue.  Let me know if you have any problems with it
